### ISSUE TITLE
Add user throws error

### ISSUE THREAD

**Issue by Katrienvh** [sumocoders/FrameworkUserBundle#14]
Add user throws error 
"Catchable Fatal Error: Argument 4 passed to SumoCoders\FrameworkSearchBundle\Entity\IndexItem::createMultipleObjectsBasedOnProperties() must be an instance of stdClass, instance of SumoCoders\FrameworkUserBundle\Entity\User given, called in /home/sites/sumocoders/framework.dev/vendor/sumocoders/framework-user-bundle/SumoCoders/FrameworkUserBundle/Controller/UserController.php on line 113 and defined"

**Comment by WouterSioen** [comment]
Die is ondertussen al gefixed. In het framework heb ik een PR  gedaan om de nieuwste versie van de search bundle te gebruiken. Dat fixed dit issue
